### ISSUE TITLE
IO::Handle's error() method does not accurately reflect write errors

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12783]
Migrated from [rt.perl.org#116807](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=116807) (status was 'open')

Searchable as RT116807$

**Comment by p5pRT** [comment]
### From tchrist@perl.com

The documentation for IO&#8203;::Handle reads&#8203;:

&nbsp;   $io\->error
&nbsp;      Returns a true value if the given handle has experienced any errors
&nbsp;      since it was opened or since the last call to "clearerr"\, or if the
&nbsp;      handle is invalid\. It only returns false for a valid handle with no
&nbsp;      outstanding errors\.

However\, this is not true\.  For example\, a failed write on a given handle
can set errno to ENOSPC\, yet fail to be noted by the error\(\) method on that
handle\.  This is shown by the enclosed test script\, which is designed to
trigger an error on the write\.  You can tell that there is a bug because
it emits&#8203;:

&nbsp;    syswrite failed\, errno was ENOSPC \(28\)&#8203;: No space left on device
&nbsp;    ERROR&#8203;: path\_fh is not in an error state after failed syswrite\.

Tested on v5\.8\.8 up through blead\.

\-\-tom

\#\!/usr/bin/env perl

use v5\.6;
use strict;
use warnings;
use warnings FATAL => qw\(deprecated closure syntax\);
use sigtrap;

use Carp;
use Errno;
use Fcntl;
use IO&#8203;::Handle;

use constant \{
&nbsp;    \# this is only needed if /dev/full isn't around
&nbsp;    FILE\_ON\_FULL\_FILESYSTEM => "/Volumes/TCHRISTFOB1/full/bar"\,
\};

main\(\);
exit\(\);

sub main \{
&nbsp;    local $SIG\{\_\_WARN\_\_\} = sub \{ confess "fatalized warning @&#8203;\_" \};
&nbsp;    STDOUT\->autoflush\(1\);
&nbsp;    test\_file\(\);
&nbsp;    print "\\nThat's all\, folks\!\\n";
\}

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#


sub test\_file \{
&nbsp;    my $file = \(\-c "/dev/full"\) ? "/dev/full" : FILE\_ON\_FULL\_FILESYSTEM;
&nbsp;    test\_write\($file\);
\}

sub test\_write \{
&nbsp;    my\($path\_name\, $is\_big\) = @&#8203;\_;
&nbsp;    my $path\_fh;

&nbsp;    my $reopen = sub \{
&nbsp;    $path\_fh = undef;

&nbsp;    sysopen\($path\_fh\, $path\_name\, O\_WRONLY | O\_APPEND\)
&nbsp;        || confess "can't sysopen $path\_name&#8203;: $\!";
&nbsp;    print "opened $path\_name for append\\n";
&nbsp;    binmode\($path\_fh\);
&nbsp;    $path\_fh\->autoflush\(1\);
&nbsp;    \};

&nbsp;    my $string = "\[this is the line of test data\]\\n";
&nbsp;    if \($is\_big\) \{
&nbsp;    $string x= 1\_000;
&nbsp;    \}

&nbsp;    my $slen = length\($string\);

&nbsp;    print "\\ntesting syswrite\\n";

&nbsp;    &$reopen;

&nbsp;    my $written = syswrite\($path\_fh\, $string\, $slen\);
&nbsp;    if \(defined $written\) \{
&nbsp;    print "ERROR&#8203;: expected write to fail\, but syswrote $written bytes\\n\\n";
&nbsp;    if \($written \!= $slen\) \{
&nbsp;        print "But I wanted to write $slen bytes\.\\n";
&nbsp;    \}
&nbsp;    \} else \{
&nbsp;    my $errno = $\! || confess "expected errno";
&nbsp;    my $has\_error = $path\_fh\->error;
&nbsp;    print "syswrite failed\, errno was "\, fmt\_errno\($errno\)\, "\\n";
&nbsp;    if \(my $has\_error = $path\_fh\->error\) \{
&nbsp;        print "path\_fh error was "\, fmt\_bool\($has\_error\)\, "\\n";
&nbsp;    \} else \{
&nbsp;        print "ERROR&#8203;: path\_fh is not in an error state after failed syswrite\.\\n";
&nbsp;    \}
&nbsp;    \}
&nbsp;    my $good\_writes = defined\($written\);

&nbsp;    my $reclose = sub \{
&nbsp;    if \(close\($path\_fh\)\) \{
&nbsp;        if \($good\_writes\) \{
&nbsp;        print "correctly closed $path\_name\\n";
&nbsp;        \} else \{
&nbsp;        print "ERROR&#8203;: expected close to fail\, since writing failed\\n";
&nbsp;        \}
&nbsp;    \} else \{
&nbsp;        if \($good\_writes\) \{
&nbsp;        print "ERROR&#8203;: expected good close\, but't close $path\_name&#8203;: "\,
&nbsp;            fmt\_errno\($\!\)\, "\\n";
&nbsp;        \} else \{
&nbsp;        print "As expected with write errors\, can't close $path\_name&#8203;: "\,
&nbsp;            fmt\_errno\($\!\)\, "\\n";
&nbsp;        \}
&nbsp;    \}
&nbsp;    \};
&nbsp;    &$reclose;

&nbsp;    &$reopen;
&nbsp;    print "\\ntesting print\\n";

&nbsp;    my $ok = print $path\_fh $string;
&nbsp;    if \($ok\) \{
&nbsp;    print "ERROR&#8203;: Print of $slen successful\.\\n";
&nbsp;    \}
&nbsp;    else \{
&nbsp;    my $errno = $\! || confess "expected errno";
&nbsp;    my $has\_error = $path\_fh\->error;
&nbsp;    print "print failed\, errno was "\, fmt\_errno\($errno\)\, "\\n";

&nbsp;    if \($has\_error\) \{
&nbsp;        print "path\_fh error was "\, fmt\_bool\($has\_error\)\, "\\n";
&nbsp;    \} else \{
&nbsp;        print "ERROR&#8203;: path\_fh is not in an error state after failed print\.\\n";
&nbsp;    \}
&nbsp;    \}

&nbsp;    $good\_writes = $ok;
&nbsp;    &$reclose;

\}

sub fmt\_bool \{
&nbsp;    my\($bool\) = @&#8203;\_;
&nbsp;    return $bool ? "TRUE" : "FALSE";
\}

sub fmt\_undef \{
&nbsp;    my\($scalar\) = @&#8203;\_;
&nbsp;    return defined\($scalar\) ? $scalar : "UNDEF";
\}

BEGIN \{

&nbsp;    my @&#8203;\_Errno2Sym;
&nbsp;    for my $errname \( grep /^E\\p\{Lu\}\+$/\, @&#8203;Errno&#8203;::EXPORT\_OK \) \{
&nbsp;    my $errnum = do \{
&nbsp;        no strict "refs";
&nbsp;        &\{"Errno&#8203;::$errname"\};
&nbsp;    \};
&nbsp;    $\_Errno2Sym\[$errnum\] = $errname;
&nbsp;    \}

&nbsp;    sub fmt\_errno \{
&nbsp;    my $num = 0 \+ $\_\[0\];
&nbsp;    my $strerror = do \{
&nbsp;        local $\! = $num;
&nbsp;        "$\!";
&nbsp;    \};
&nbsp;    my $esym = $\_Errno2Sym\[$num\] || "unknown error number \#$num";
&nbsp;    return "$esym \($num\)&#8203;: $strerror";
&nbsp;    \}

\}

\_\_END\_\_

testing syswrite
opened /Volumes/TCHRISTFOB1/full/bar for append
syswrite failed\, errno was ENOSPC \(28\)&#8203;: No space left on device
ERROR&#8203;: path\_fh is not in an error state after failed syswrite\.
ERROR&#8203;: expected close to fail\, since writing failed
opened /Volumes/TCHRISTFOB1/full/bar for append

testing print
print failed\, errno was ENOSPC \(28\)&#8203;: No space left on device
path\_fh error was TRUE
As expected with write errors\, can't close /Volumes/TCHRISTFOB1/full/bar&#8203;: ENOSPC \(28\)&#8203;: No space left on device

That's all\, folks\!

================================================================

Summary of my perl5 \(revision 5 version 16 subversion 0\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=darwin\, osvers=9\.8\.0\, archname=darwin\-2level
&nbsp;    uname='darwin tom\-christiansens\-macbook\-pro\-2\.local 9\.8\.0 darwin kernel version 9\.8\.0&#8203;: wed jul 15 16&#8203;:55&#8203;:01 pdt 2009; root&#8203;:xnu\-1228\.15\.4~1release\_i386 i386 '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-common \-DPERL\_DARWIN \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-I/opt/local/include'\,
&nbsp;    optimize='\-O3'\,
&nbsp;    cppflags='\-fno\-common \-DPERL\_DARWIN \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-I/opt/local/include'
&nbsp;    ccversion=''\, gccversion='4\.0\.1 \(Apple Inc\. build 5493\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='env MACOSX\_DEPLOYMENT\_TARGET=10\.3 cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib \-L/opt/local/lib'
&nbsp;    libpth=/usr/local/lib /opt/local/lib /usr/lib
&nbsp;    libs=\-lgdbm \-ldbm \-ldb \-ldl \-lm \-lutil \-lc
&nbsp;    perllibs=\-ldl \-lm \-lutil \-lc
&nbsp;    libc=\, so=dylib\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=bundle\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags=' \-bundle \-undefined dynamic\_lookup \-L/usr/local/lib \-L/opt/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_MALLOC\_WRAP PERL\_PRESERVE\_IVUV USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under darwin
&nbsp;  Compiled at Jul 15 2012 13&#8203;:29&#8203;:37
&nbsp;  %ENV&#8203;:
&nbsp;    PERL\_UNICODE="S"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.16\.0/darwin\-2level
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.16\.0
&nbsp;    /usr/local/lib/perl5/5\.16\.0/darwin\-2level
&nbsp;    /usr/local/lib/perl5/5\.16\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.13\.9
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.13\.8
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.13\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.12\.3
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.12\.2
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.11\.3
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.10\.0
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Feb 17 15&#8203;:16&#8203;:54 2013\, tom christiansen wrote&#8203;:
> The documentation for IO&#8203;::Handle reads&#8203;:
\.\.\.

Confirming that I got the same output as Tom on Linux/i386\.

jimk

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by tonycoz** [comment]
I believe this was fixed by 89341f87f (which itself needed a fix in 8a2562bec

**Comment by jkeenan** [comment]
> I believe this was fixed by [89341f8](https://github.com/Perl/perl5/commit/89341f87f9fc65c4d7133e497bb04586e86b8052) (which itself needed a fix in [8a2562b](https://github.com/Perl/perl5/commit/8a2562bec7cd9f8eff6812f340f99dddd028bb33)

I don't think so.  Somewhat to my surprise, I found Tom's test program on my server exactly where I placed it 11 years ago.  I ran it and got what appear to be the same results as I did then and as Tom did.
```
$ perl 116807_iohandle_write.pl 

testing syswrite
opened /dev/full for append
syswrite failed, errno was ENOSPC (28): No space left on device
ERROR: path_fh is not in an error state after failed syswrite.
ERROR: expected close to fail, since writing failed
opened /dev/full for append

testing print
print failed, errno was ENOSPC (28): No space left on device
path_fh error was TRUE
As expected with write errors, can't close /dev/full: ENOSPC (28): No space left on device

That's all, folks!
```
That suggests to me that the problem is still present, hence the ticket is not closable.
