### ISSUE TITLE
Backtick/qx operations fail under Windows

### ISSUE THREAD

**Issue by georgealverson** [Perl/perl5#19826]
Example: 
perl -e 'print qx(date /T);'

Expected output (example):
Sun 06/056/2022 

Actual output: none, but there is a zero length file name date in the current directory.

Example of a possible workaround (thanks to Håkon Hægland, https://stackoverflow.com/questions/72503807/perl-calls-using-system-abruptly-start-failing)
 
perl -e 'print qx($ENV{COMSPEC} /C DATE /T)';
Sun 06/05/2022

Suspected cause: some security patch changed Windows behavior?

---
Flags:
    category=core
    severity=high
---
Site configuration information for perl 5.32.1:

Configured by strawberry-perl at Sun Jan 24 15:01:28 2021.

Summary of my perl5 (revision 5 version 32 subversion 1) configuration:
   
  Platform:
    osname=MSWin32
    osvers=10.0.19042.746
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.32.1.1 #1 Sun Jan 24 15:00:15 2021 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\Users\USER\AppData\Local\Programs\STRAWB~1\perl\lib\CORE" -L"C:\Users\USER\AppData\Local\Programs\STRAWB~1\c\lib"'
    libpth=C:\Users\USER\AppData\Local\Programs\STRAWB~1\c\lib C:\Users\USER\AppData\Local\Programs\STRAWB~1\c\x86_64-w64-mingw32\lib C:\Users\USER\AppData\Local\Programs\STRAWB~1\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl532.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\Users\USER\AppData\Local\Programs\STRAWB~1\perl\lib\CORE" -L"C:\Users\USER\AppData\Local\Programs\STRAWB~1\c\lib"'

---
@INC for perl 5.32.1:
    C:/Users/USER/AppData/Local/Programs/Strawberry/perl/site/lib/MSWin32-x64-multi-thread
    C:/Users/USER/AppData/Local/Programs/Strawberry/perl/site/lib
    C:/Users/USER/AppData/Local/Programs/Strawberry/perl/vendor/lib
    C:/Users/USER/AppData/Local/Programs/Strawberry/perl/lib

---
Environment for perl 5.32.1:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.4.0_x64__8wekyb3d8bbwe;C:\Users\USER\AppData\Local\Programs\CollabNet\Subversion Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\USER\AppData\Local\Programs\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Users\USER\AppData\Local\Programs\Strawberry\c\bin;C:\Users\USER\AppData\Local\Programs\Strawberry\perl\site\bin;C:\Users\USER\AppData\Local\Programs\Strawberry\perl\bin;C:\Program Files\Microsoft SQL
Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\PowerShell\7\;C:\Users\USER\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\USER\AppData\Local\Programs\Python\Python310\;C:\Users\USER\AppData\Local\Microsoft\WindowsApps;C:\Users\USER\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\bin
    PERL_BADLANG (unset)
    SHELL (unset)

**Comment by tonycoz** [comment]
> perl -e 'print qx(date /T);'
> 
> Expected output (example): Sun 06/056/2022

If I run with a recent blead:
```
C:\Users\Tony\dev\perl\git\perl\win32>..\perl -e "print qx(date /t)"
Mon 06/06/2022
```

If I use strawberry perl 5.32.1 like the linked stackoverflow user does:

```
Perl executable: c:\strawberry-perl-5.32.1.1-64bit-portable\perl\bin\perl.exe
Perl version   : 5.32.1 / MSWin32-x64-multi-thread

C:\>perl -e "print qx(date /t)"
Mon 06/06/2022
```

This was on Windows 10, without the 21H2 feature update.

To run your example using single quotes, I need to use powershell, otherwise the code fails to compile:
```
C:\Users\Tony\dev\perl\git\perl\win32>..\perl -I..\lib -e 'print qx(date /t)'
Can't find string terminator "'" anywhere before EOF at -e line 1.

PS C:\Users\Tony> perl -e 'print qx(date /t)'
Mon 06/06/2022
```

If you have a debug build of perl running with `-Dp` might provide some information, ie.:
```
perl -Dp -e 'print qx(date /t)'
```

**Comment by georgealverson** [comment]
Hi Tony,

Do you have a link for a debug build? I tried it myself, and as the SO link shows, the build dies in miniperl.

I have another box with a slightly older version of strawberry perl that shows no problems.

Best,
George

**Comment by tonycoz** [comment]
In your perl build directory (where miniperl failed), try running miniperl with the -Dp switch:
```
..\miniperl.exe -Dp -I..\lib ..\make_ext.pl "MAKE=nmake -nologo" --dir=..\cpan --dir=..\dist --dir=..\ext --nonxs
```

What's the value of COMSPEC?

If you run "cmd.exe" directly from whichever shell you're using, does it run "C:\WINDOWS\system32\cmd.exe" or some other cmd.exe?  (you can see the path to the executable in the details tab of Task Manager if you turn on the "Image path name" column.)

**Comment by georgealverson** [comment]
Dear Tony,

**Setting PERL5SHELL as  C:\\WINDOWS\\system32\\cmd.exe /C seems to allow my existing perl scripts to run without modification [system calls also require complete path]. Below is the original debugging information. [Thanks to BWiz on StackOverflow.]**

Here is the tail of the output of the miniperl execution (running from the x64 Native Tools shell) :

```Reading a token:
Now at end of input.
lookahead token is token "end of file" (0xffffffffb8521e48)
Reducing stack by rule 2 (line 139), GRAMPROG @1 remember stmtseq -> grammar
Entering state 8
lookahead token is token "end of file" (0xffffffffb8521e48)
clearing the parse stack
Args [nmake][-nologo][all][PERL_CORE=1]
Spawning [nmake] with [nmake -nologo all PERL_CORE=1]
Retrying [nmake] with same args
Args [cmd.exe][/x/d/c][nmake][-nologo][all][PERL_CORE=1]
Spawning [cmd.exe] with [cmd.exe /x/d/c "nmake -nologo all PERL_CORE=1"]
Retrying [cmd.exe] with same args
Can't spawn "cmd.exe": No such file or directory at ..\make_ext.pl line 580.
Args [nmake][-nologo][all][PERL_CORE=1]
Spawning [nmake] with [nmake -nologo all PERL_CORE=1]
Retrying [nmake] with same args
Args [cmd.exe][/x/d/c][nmake][-nologo][all][PERL_CORE=1]
Spawning [cmd.exe] with [cmd.exe /x/d/c "nmake -nologo all PERL_CORE=1"]
Retrying [cmd.exe] with same args
Can't spawn "cmd.exe": No such file or directory at ..\make_ext.pl line 582.
Unsuccessful make(dist/if): code=65280 at ..\make_ext.pl line 584.```

COMSPEC:
perl -e 'print "$ENV{COMSPEC}"';
C:\WINDOWS\system32\cmd.exe

CMD:
Everything seems to indicate that there is only the one cmd. 
1.  Task Manager shows a file location of C:\Windows\System32\cmd.exe for cmd.exe
2.   pwsh shows only one, 
3. get-command -all cmd | Format-Table

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     cmd.exe                                            10.0.2200… C:\WINDOWS\system32\cmd.exe
4.  cmd itself gives that location: 
5. where cmd
C:\Windows\System32\cmd.exe

Just let me know if there is anything else!

Best,
George

NOTE:
I found that explicitly setting PERL5SHELL allows the process to continue (although it does die later):

echo %PERL5SHELL%
"C:/Windows/System32/cmd.exe"

...
lookahead token is token "end of file" (0x46f0dbb8)
clearing the parse stack
Args [nmake][-nologo][all][PERL_CORE=1]
Spawning [nmake] with [nmake -nologo all PERL_CORE=1]
Retrying [nmake] with same args
Args ["C:/Windows/System32/cmd.exe"][nmake][-nologo][all][PERL_CORE=1]
Spawning [C:/Windows/System32/cmd.exe] with ["C:/Windows/System32/cmd.exe" nmake -nologo all PERL_CORE=1]
Args [C:\Users\galve\source\repos\foreign\perl5\miniperl.exe][-I../../lib][Makefile.PL][INSTALLDIRS=perl][INSTALLMAN1DIR=none][INSTALLMAN3DIR=none][PERL_CORE=1][PERL=C:\Users\galve\source\repos\foreign\perl5\miniperl.exe]
Spawning [C:\Users\galve\source\repos\foreign\perl5\miniperl.exe] with [C:\Users\galve\source\repos\foreign\perl5\miniperl.exe -I../../lib Makefile.PL INSTALLDIRS=perl INSTALLMAN1DIR=none INSTALLMAN3DIR=none PERL_CORE=1 PERL=C:\Users\galve\source\repos\foreign\perl5\miniperl.exe]
Generating a nmake-style Makefile
Writing Makefile for lib
Args [nmake][-nologo][all][PERL_CORE=1]
Spawning [nmake] with [nmake -nologo all PERL_CORE=1]
Retrying [nmake] with same args
Args ["C:/Windows/System32/cmd.exe"][nmake][-nologo][all][PERL_CORE=1]
Spawning [C:/Windows/System32/cmd.exe] with ["C:/Windows/System32/cmd.exe" nmake -nologo all PERL_CORE=1]
Args [perlglob][*]
Spawning [perlglob] with [perlglob *]
Retrying [perlglob] with same args
Args ["C:/Windows/System32/cmd.exe"][perlglob *]
Args ["C:/Windows/System32/cmd.exe"][perlglob *]
Spawning [C:/Windows/System32/cmd.exe] with ["C:/Windows/System32/cmd.exe" "perlglob *"]
The filename, directory name, or volume label syntax is incorrect.
Error occurred while processing: *.
Args [C:\Users\galve\source\repos\foreign\perl5\miniperl.exe][-I../../lib][Makefile.PL][INSTALLDIRS=perl][INSTALLMAN1DIR=none][INSTALLMAN3DIR=none][PERL_CORE=1][PERL=C:\Users\galve\source\repos\foreign\perl5\miniperl.exe]

**Comment by oldcoder47** [comment]
I have the same problem on all four of my machines, which run ActiveState Perl.  I tried installing Strawberyy Perl, but it had the same problem.  One of my machines is a Dell Precision running WinVer 1909 18363.1556 and ActiveState Perl 5.26.3.  Latest updates are KB5003169 May 03 and KB5003244 May 01.  The other 3 machines are HP Elite 8300 running Winver 21H2 19044.1706 and ActiveState Perl 5.24.1.
set PERL5SHELL=c:\\WINDOWS\\system32\\cmd.exe /c 
in my login.bat resolves most of the problems, but I still get 0-length files being created even though the Perl script works.  E.g., 
`<backtick>msg * HI<backtick>`
will pop up a message box containing "Hi", but it also leaves a length 0 file msg in the directory where I ran the program.
`<backtick>C:\\WINDOWS\\system32\\msg.exe * Hi<backtick>`
works and does not produce a spurious msg file.
The spurious files so created can break Perl scripts in future runs.
Adding full paths to all the system() and backtick calls in the scripts I have written over the last 25 years is a big job, so I hope you can solve this problem.

**Comment by georgealverson** [comment]
One thing I have found by starting from a bare box is that the problem occurs when Malwarebytes is installed (and persists even after it is removed).

**Comment by oldcoder47** [comment]
Great find! I turned off my MalwareBytes protection and re-ran a test case and found that turning off MB at the GUI level resolved at least one of the issues I was having -- Namely the created of spurious files. I will come up with a simpler test case that I can send to MB and let everyone know.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by oldcoder47** [comment]
I see someone else reported this to the MalwareBytes forum:
https://forums.malwarebytes.com/topic/287533-strawberry-perl-being-blocked/
but that person evidently just uninstalled MB and did not want to get involved in troubleshooting, so MB will probably not act on that report. The reporter stated that he/she could just use cygwin Perl.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by georgealverson** [comment]
I created a trouble ticket at MWB on 2022-06-11. Haven't heard back from them yet.

**Comment by oldcoder47** [comment]
I did not see your ticket.  I created my own ticket 3894501.  I got an ACK a few minutes later, so maybe they lost yours.

**Comment by georgealverson** [comment]
Using the Malwarebytes beta (4.5.10.200) version fixes this problem, so far. One can never tell with a beta, but I'm using it for now.

Still interested to learn how the problem persisted even if I deinstalled MWB.
